export const CHANGE_SEARCH_FIELD='CHANGE_SEARCHFIELD';

export const REQUESTS_ROBOTS_PENDING='REQUESTS_ROBOTS_PENDING';
export const REQUESTS_ROBOTS_SUCCESS='REQUESTS_ROBOTS_SUCCESS';
export const REQUESTS_ROBOTS_FAILED='REQUESTS_ROBOTS_FAILED';